name: Issue Template
description: こちらは新しいIssueを作成する際に使用するテンプレートです。
title: ''
labels: ''
assignees: ''

body:
  - type: markdown
    attributes:
      value: "## 目的\nこのIssueが解決しようとしている問題や、達成しようとしている目的を明確に記述してください。"

  - type: input
    id: purpose
    attributes:
      label: 目的
      description: "このIssueで解決したい問題、または達成したいことを明確にしてください。"
      placeholder: "例: ユーザーのログイン速度を改善する"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## やること\nこのIssueで具体的にどのような作業を行うのかを記述してください。"

  - type: textarea
    id: tasks
    attributes:
      label: やること
      description: "実施する作業や対応内容を具体的に列挙してください。"
      placeholder: "- ログインAPIのパフォーマンスを最適化\n- キャッシュの導入"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## リリースタイミング\nこのIssueの成果物がリリースされるタイミングや、その必要性がある場合の締め切りを記述してください。"

  - type: input
    id: release_timing
    attributes:
      label: リリースタイミング
      description: "リリースのタイミングや期日がある場合に記載してください。"
      placeholder: "例: 次回リリーススプリント"

  - type: markdown
    attributes:
      value: "## 補足\n追加の情報や、このIssueに関連するリンクやメモがあれば記載してください。"

  - type: textarea
    id: additional_info
    attributes:
      label: 補足
      description: "特筆すべき点や補足情報があればこちらに記載してください。"
      placeholder: "例: 関連するPRやIssueへのリンク"
